version: "3"
services:
  adguard:
    image: tob123/adguard-staging:${VERSION}
    build: ./
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped
volumes:
  adguard_work:
  adguard_conf:
